#!/usr/bin/env bash

session=$(find ~ ~/Documents ~/Documents/dev ~/Documents/dev/labs -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename $session | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$session" -d
fi

# Check if the script is running inside tmux
if [ -z "$TMUX" ]; then
    # Not running inside tmux
    tmux attach-session -t "$session_name"
else
    # Running inside tmux
    tmux switch-client -t "$session_name"
fi
